version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: energy-trading-db
    environment:
      POSTGRES_DB: energy_trading
      POSTGRES_USER: energy_user
      POSTGRES_PASSWORD: energy_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./energy-trading-rust/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U energy_user -d energy_trading"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
